name: Build Docs

on: [push]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.4

    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Setup dependencies
      run: luarocks install --only-deps https://raw.githubusercontent.com/lunarmodules/LDoc/master/ldoc-scm-3.rockspec

    - name: Checkout & build docs
      run: git clone --branch=build_docs https://github.com/lunarmodules/LDoc.git ldoc && cd ldoc && chmod +x build_versioned_docs.sh && ./build_versioned_docs.sh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ldoc/doc_builds/